name: FreyrsProsperity
version: 1.0
main: wbe.freyrsProsperity.FreyrsProsperity
api-version: 1.21
author: wbe
softdepend: [PlaceholderAPI]
depend: [DecentHolograms, mythicmobs]
commands:
  FreyrsProsperity:
    description: FreyrsProsperity main command
    aliases: [fp, freyrsp, fprosperity]
    permission: freyrsprosperity.command